version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    working_directory: ~/reportcard-rails
    docker:
      - image: circleci/ruby:2.7.4
        environment:
          PGHOST: localhost
          PGUSER: reportcard-rails
          RAILS_ENV: test
      - image: postgres:14.4
        environment:
          POSTGRES_USER: reportcard-rails
          POSTGRES_DB: reportcard-rails_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: reportcard-rails
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:migrate
      - run: bundle exec rspec

workflows:
  build-workflow:
    jobs:
      - build

  heroku-workflow:
    jobs:
      - heroku/deploy-via-git:
          force: true 
          app-name: reportcard-rails
          api-key: HEROKU_API_KEY
          branch: main